// packages/vue-l/src/components/TodoList.vue
<script setup lang="ts">
import { ref, reactive } from 'vue'
import { $ref } from 'vue/macros';

// import { $ref } from "vue/macros";
import InputValue from './Input.vue'
import MyList from './List.vue'

interface Item {
  name: string
  id: string
}
let count = 0
const list = reactive<Item[]>([])

const onChange = (value: string) => {
  list.push({ name: `${value}`, id: `${count++}` })
}

const onDelete = (idx: number) => {
  list.splice(idx, 1)
}

</script>

<template>
  <div className='flex justify-center flex-col max-w-500px mx-auto'>
      <InputValue @onClick='onChange' />
      <MyList :list='list' @onDelete='onDelete' />
  </div>
</template>

<style scoped>

</style>

// packages/svelte-l/src/lib/TodoList.svelte
<script lang="ts">
import InputValue from "./InputValue.svelte";
import List from "./List.svelte";

interface Item {
  name: string
  id: string
}
let list: Item[] = $state([])
let count = $state(0)

const onChange = (value: any) => {

  list = [...list, {
    name: value,
    id: `${count++}`
  }]
}
const  onDelete = (idx: number) => {
  list.splice(idx, 1)
  list = list
}

$effect(() => {
  console.log('更新状态....',list)
})

</script>

<div class='flex justify-center flex-col max-w-500px mx-auto'>
  <InputValue handleClick={onChange} />
  <List list={list} onDelete={onDelete} />
</div>

<style>
</style>
